spring:
  application:
    name: clinic

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  port: 8080

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  max-image-mb: 5
  max-pdf-mb: 10

payhere:
  sandbox: true
  merchant-id: ${PAYHERE_MERCHANT_ID}
  merchant-secret: ${PAYHERE_MERCHANT_SECRET}
  currency: LKR
  return-url: ${FRONTEND_URL}/payment/success
  cancel-url: ${FRONTEND_URL}/payment/cancel
  notify-url: ${BACKEND_URL}in/api/payments/payhere/notify

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 604800000

app:
  frontend-url: ${FRONTEND_URL}
  base-url: ${BACKEND_URL}
  reminder:
    cron: "0 */5 * * * *"